
version: "3"

services:
  # presentation
  #   Server for hosting the main keynote provider.
  presentation:
    restart: always
    build: .
    container_name: presentation
    depends_on:
      - autoindex
    ports:
      - 8000:8000
    volumes:
      - "outcache:/Content:rw"
      - "./Slides:/Content/Slides:ro"
      - "./Images:/Content/Images:ro"

  # autoindex
  #   An instance to monitor input changes and write to the index file.
  autoindex:
    restart: always
    build: ./I-Notify
    container_name: autoindex
    volumes:
      - "outcache:/output:rw"
      - "./I-Notify:/tools:ro"
      - "./Shared:/defaults:ro"
      - "./Slides:/watch:ro"
    entrypoint: /tools/Make.sh

volumes:
  # outcache
  #   A shared volume for keeping autoindex-generated files alive, whilst also
  #   parsing and serving that content on a port from the 'presentation'
  #   container.
  outcache:
