
version: "3"

services:
  # presentation
  #   Server for hosting the main keynote provider.
  presentation:
    restart: always
    build: .
    container_name: presentation
    ports:
      - 8000:8000
    volumes:
      - "./Shared:/Content:rw"
      - "./Slides:/Content/Slides:ro"
      - "./Images:/Content/Images:ro"

  # autoindex
  #   An instance to monitor input changes and write to the index file.
  autoindex:
    restart: always
    build: ./I-Notify
    container_name: autoindex
    volumes:
      - "./Slides:/watch:ro"
      - "./I-Notify:/tools:rw"
      - "./Shared/index.qmd:/output.qmd:rw"
    entrypoint: /tools/Make.sh
