
project:
  output-dir: _output
  render:
    - index.qmd
css: _style.css

format: revealjs
title: "Presentation"
controls-layout: bottom-right
navigation-mode: grid
menu: false
view-distance: 3

# Table of contents
# toc: true
# toc-depth: 1

# Theme
theme: night
logo: Images/Kermit.jpg
slide-number: h.v
transition: slide
